name: Flutter PR Review

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  flutter_review:
    name: Flutter Analyze & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze

      # Only include the test run if you have written tests in your 'test/' folder
      # - run: flutter test
